export const englishUI = {
  الرئيسية: "Home",
  "جميع المشاريع": "Projects",
  الخدمات: "Services",
  كتاباتي: "Writing",
  "سيرتي الذاتية": "Resume",
  "تواصل معي": "Contact me",
  عربي: "Araby",
  "محمود عربي": "Mahmoud Araby",
  "التنقل الرئيسي": "Main navigation",
  "فتح القائمة الرئيسية": "Open main menu",
  "إغلاق القائمة": "Close menu",
  "القائمة الرئيسية": "Main menu",
  "روابط التواصل": "Contact links",
  "© 2026 محمود عربي. جميع الحقوق محفوظة.":
    "© 2026 Mahmoud Araby. All rights reserved.",
  "انتقل إلى المحتوى": "Skip to content",
  "أدوات سريعة": "Quick actions",
  "العودة لأعلى الصفحة": "Back to top",
  "الوضع الداكن": "Dark mode",
  داكن: "Dark",
  فاتح: "Light",
  التنقل: "Navigation",
  "عن محمود": "About me",
  "الخدمات والتخصصات": "Services",
  "السيرة الذاتية (CV)": "Resume (CV)",
  "واتساب (WhatsApp)": "WhatsApp",
  "حساباتي على السوشيال ميديا": "My social profiles",
  "متاح للمشاريع الجديدة والاستشارات":
    "Available for new projects and consultations",
  "صُمم وبُني بعناية فائقة وشغف بتصميم المنتجات الرقمية.":
    "Designed and built with care and a passion for digital products.",
  "© 2026 جميع الحقوق محفوظة لـ ": "© 2026 All rights reserved. ",
  "مصمم UX/UI بخبرة أكثر من 4 سنوات في تصميم المنتجات والتجارب الرقمية، من المواقع الإلكترونية وتطبيقات الموبايل إلى لوحات التحكم والأنظمة الرقمية.":
    "UX/UI designer with over 4 years of experience designing digital products and experiences, from websites and mobile apps to dashboards and digital platforms.",
  "زيارة الموقع": "Visit website",
  "متجر أبل": "App Store",
  "متجر جوجل": "Google Play",
  "روابط المشروع": "Project links",
  "جميع مشاريعي": "All projects",
  "تصفية المشاريع": "Filter projects",
  "عرض المزيد": "Show more",
  "لا توجد مشاريع منشورة في هذا التصنيف حاليًا.":
    "No projects have been published in English in this category yet.",
  الكل: "All",
  "تطبيقات الجوال": "Mobile apps",
  "منصات الويب & SaaS": "Web & SaaS",
  "لوحات التحكم & Dashboards": "Dashboards",
  "الجهات الحكومية": "Government",
  "عن المشروع": "About the project",
  التحدي: "The challenge",
  "المشكلة التي يعالجها المشروع": "The problem to solve",
  الحل: "The solution",
  "كيف تعاملت مع المشروع": "My approach",
  "ما الذي احتاجته التجربة؟": "What did the experience need?",
  "طريقة العمل": "How I worked",
  "خارطة الطريق": "Roadmap",
  "من فهم المشكلة إلى عرض الواجهات والتفاصيل النهائية.":
    "From understanding the problem to the final interface and its details.",
  "نتيجة المشروع": "The outcome",
  "اقرأ المزيد": "Read more",
  "عرض أقل": "Read less",
  "نطاق المشروع": "Project scope",
  المجال: "Industry",
  الفترة: "Period",
  العميل: "Client",
  "مدة المشروع": "Project duration",
  "تصميم تجربة وواجهة المستخدم": "UX/UI design",
  "تطبيق جوال": "Mobile app",
  "موقع إلكتروني": "Website",
  "لوحة تحكم": "Dashboard",
  "خدمات حكومية": "Government services",
  الجوائز: "Awards",
  "الجوائز والتقدير": "Awards and recognition",
  "تقدير العمل": "Recognition",
  "نبدأ مشروعك القادم؟": "Let’s start your next project",
  "اختار الطريقة المناسبة وشاركني تفاصيل فكرتك.":
    "Choose how to connect and tell me about your idea.",
  "حجز استشارة": "Book a consultation",
  "احجز استشارة": "Book a consultation",
  "تواصل عبر البريد": "Send an email",
  "اكتشف جميع الشاشات": "Explore all screens",
  "مشاريع أخرى": "More projects",
  "إغلاق المشروع والعودة إلى جميع المشاريع":
    "Close project and return to projects",
  "البحث والاستكشاف": "Research and discovery",
  "فهم المشكلة والمستخدم": "Understand the problem and users",
  "مراجعة التجارب المشابهة": "Review similar experiences",
  "تحديد الأولويات": "Set priorities",
  "تجربة المستخدم": "User experience",
  "تنظيم المحتوى": "Organize content",
  "تدفقات الاستخدام": "User flows",
  "تصور الشاشات": "Wireframes",
  "تصميم الواجهات": "Interface design",
  "الاتجاه البصري": "Visual direction",
  "تفاصيل التفاعل": "Interaction details",
  "عرض التصميم النهائي": "Present the final design",
  "التصميم النهائي": "Final design",
  "أسئلة قبل أن نبدأ": "Before we start",
  "إجابات تساعدك تعرف الخطوة الجاية.":
    "Answers to help you take the next step.",
  "ولو عندك سؤال مختلف، يسعدني أسمعه.":
    "Have another question? I’d love to hear it.",
  "كلمني بسرعة على واتساب": "Chat with me on WhatsApp",
  "كلمني بسرعة": "Let’s talk",
  "آراء عملائي": "Client feedback",
  "كلمات من القلب": "Words from the heart",
  "تغيير آراء العملاء": "Browse client feedback",
  التاريخ: "Date",
  "جميع كتاباتي": "All writing",
  "كتابات جديدة قريبًا.": "New writing in English is coming soon.",
  "إغلاق المقال والعودة إلى جميع كتاباتي":
    "Close article and return to writing",
  "فتح الرابط": "Open link",
  "محتوى تجريبي لمعاينة التصميم": "Sample content for the design preview",
  "السيرة الذاتية": "Resume",
  "سيرتي PDF": "Resume PDF",
  "الخبرات العملية": "Work experience",
  "أدوات أستخدمها في عملي": "Tools I work with",
  المهارات: "Skills",
  "أبرز الأعمال والإنجازات": "Selected work and achievements",
  فيجما: "Figma",
  "فيج جام": "FigJam",
  فوتوشوب: "Photoshop",
  إليستريتور: "Illustrator",
  "بريمير برو": "Premiere Pro",
  "أفتر إفكتس": "After Effects",
  "تصميم الواجهات والنماذج التفاعلية":
    "Interface design and interactive prototypes",
  "الأفكار وخرائط تجربة المستخدم": "Ideas and experience maps",
  "معالجة الصور والتصميم البصري": "Image editing and visual design",
  "الرسوم والعناصر المتجهة": "Vector graphics and illustration",
  "تحرير الفيديو": "Video editing",
  "الحركة والمؤثرات البصرية": "Motion and visual effects",
  "تصميم المنتجات": "Product design",
  "أبحاث المستخدم": "User research",
  "مقابلات المستخدمين": "User interviews",
  "رحلات المستخدم": "User journeys",
  "هندسة المعلومات": "Information architecture",
  "اختبارات قابلية الاستخدام": "Usability testing",
  "أنظمة التصميم": "Design systems",
  "النماذج التفاعلية": "Prototyping",
  "التصميم المتجاوب": "Responsive design",
  "إمكانية الوصول": "Accessibility",
  "أنا محمود عربي، مصمم تجربة وواجهة مستخدم بخبرة أكثر من ٤ سنوات. أحوّل الأفكار والأنظمة المعقدة إلى تجارب رقمية واضحة وسهلة الاستخدام.":
    "I’m Mahmoud Araby, a UX/UI designer with over 4 years of experience. I turn ideas and complex systems into clear, easy-to-use digital experiences.",
  "أفكار وتجارب عن تصميم المنتجات الرقمية وتجربة المستخدم، من فهم المشكلة إلى تفاصيل الواجهة.":
    "Thoughts and lessons on digital products and user experience, from understanding the problem to the details of the interface.",
  "اهم مشاريعي": "Selected projects",
  "مجموعة مختارة من المشاريع وتجارب المنتجات الرقمية التي عملت عليها.":
    "A selection of digital products and experiences I have designed.",
  "عرض جميع المشاريع": "View all projects",
  "عميل سعيد": "Happy clients",
  "مشروع مكتمل": "Completed projects",
  "سنوات خبرة": "Years of experience",
  خدماتي: "Services",
  "تصميم واجهة المستخدم": "User interface design",
  "تصميم الهوية البصرية": "Visual identity design",
  التطوير: "Development",
  "التطوير البرمجي": "Development",
  "مجموعة متنوعة من البرامج المتخصصة التي تلبي اهتمامات مختلفة وتقدم محتوى هادف ومميز":
    "Design and development services for digital products and brands.",
};
export const ui = (lang, text) =>
  lang === "en" ? englishUI[text] || text : text;
